default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kifo_development

test:
  <<: *default
  database: kifo_test

production:
  <<: *default
  database: kifo_production
  username: kifo
  password: <%= ENV['kifo_DATABASE_PASSWORD'] %>
